export const getUserById = async (id: string) => {
  try {
    // logic here
  } catch (error) {
    throw new Error('Something went wrong');
  }
};
